export const FETCH_UNSOLVED = 'FETCH_UNSOLVED';
export const FETCH_SOLVED = 'FETCH_SOLVED';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';

export const SET_LOCATION = 'SET_LOCATION';
export const INPUT_NUM = 'INPUT_NUM';